### ISSUE TITLE
Column1 not found

### ISSUE THREAD

**Issue by coustack** [auvik/powerbi-templates#3]
Hello, when trying to open the template I receive the error below "Column1' of the table was not found. This is for alerts, Device Inventory and Warrenty Data.

![image](https://user-images.githubusercontent.com/48837785/99719439-49f37200-2a7a-11eb-8c34-18c963d31efe.png)

**Comment by johanfeito** [comment]
Hi @coustack, 

It looks very much like the first of the error messages described in [this article](https://support.auvik.com/hc/en-us/articles/360051973172-Troubleshooting-authentication-issues-in-Power-BI) in our support page. 

Please, try the steps described in there and let us know if you're able to get it to work. Please bear in mind that part of the solution described there requires you to have [specific user settings](https://support.auvik.com/hc/en-us/articles/360052433051) in your Auvik user account, contact your admin if you need any changes. 

Let us know if that works!
Thanks
